// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttumoijdqryptsnojubl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0dW1vaWpkcXJ5cHRzbm9qdWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzc2ODYsImV4cCI6MjA2OTU1MzY4Nn0.3oxWY0BP4HthpQw7q258ot2ph29U1kWT-Ti_WV2cb1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});